{"uuid": "2909eef3-47dc-45c4-8a69-78be2c42903b", "children": ["36b9bcea-cfde-499f-bca9-4e2f6e72072f"], "befores": [{"name": "screenshot_on_failure", "status": "passed", "start": 1597851093202, "stop": 1597851093202}], "afters": [{"name": "screenshot_on_failure::fin", "status": "broken", "statusDetails": {"message": "OSError: [Errno 22] Invalid argument: 'D:\\x07utotests_screenshots\\\\scr.pnguosap3b7.png'\n", "trace": "  File \"c:\\users\\m.kononova\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\allure_commons\\_allure.py\", line 185, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\m.kononova\\environments\\flexite_autotests\\conftest.py\", line 44, in fin\n    attach = driver.screenshot('D:\\autotests_screenshots\\scr.png', full=True)\n  File \"c:\\users\\m.kononova\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\splinter\\driver\\webdriver\\__init__.py\", line 660, in screenshot\n    (fd, filename) = tempfile.mkstemp(prefix=name, suffix=suffix)\n  File \"c:\\users\\m.kononova\\appdata\\local\\programs\\python\\python38-32\\lib\\tempfile.py\", line 332, in mkstemp\n    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)\n  File \"c:\\users\\m.kononova\\appdata\\local\\programs\\python\\python38-32\\lib\\tempfile.py\", line 250, in _mkstemp_inner\n    fd = _os.open(file, flags, 0o600)\n"}, "start": 1597851097320, "stop": 1597851103581}], "start": 1597851093202, "stop": 1597851103581}